### PR TITLE
Web app summary of experimental design and plot level traits

### PR DESCRIPTION
**Pull request by nickheyek**

### CODE REVIEW

**Comment by dlebauer** [comment]
@nickheyek could you please describe the contents of the PR? Is it a web app that dynamically queries BETYdb? What are the dependencies?

**Comment by nickheyek** [comment]
The Experiment Trait Data Visualizer receives data from the BETYdb API. The code for retrieving and handling this data can be found in the api_data_retrieval directory.

Pygal is used to generate box plot visualizations for each variable in the traits endpoint of the BETYdb API. The code for generating these visualizations is in api_data_retrieval/variable_data_plotter.py.

The web interface is served as a Flask application. It serves svgs rendered by Pygal for each variable, as well as a timeline made from data in the managements enpoint of the BETYdb API.

The dependencies can be found in requirements.txt, install with 'pip install -r requirements.txt'

**Comment by dlebauer** [comment]
@nickheyek could you add the daily cache update functionality before we merge and deploy this?

**Comment by dlebauer** [comment]
I've posted the sample here: https://terraref.ncsa.illinois.edu/webapps/ua-mac/experiment-trait-data-visualizer_sample

But still can't get past the apscheduler error

**Comment by nickheyek** [comment]
Sorry, must not have update requirements.txt.
This should do it:
pip uninstall apscheduler
pip install apscheduler==2.1.2

**Comment by dlebauer** [comment]
That worked. I had installed apscheduler 3.x

But now this error:

```
[2017-05-09 23:15:42,773] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/dlebauer/anaconda/envs/python3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlebauer/anaconda/envs/python3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlebauer/anaconda/envs/python3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dlebauer/anaconda/envs/python3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/dlebauer/anaconda/envs/python3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlebauer/anaconda/envs/python3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 32, in data_summary
    management_data = get_management_data(start_date, end_date)
  File "/Users/dlebauer/terraref/reference-data/experiment-trait-data-visualizer/api_data_retrieval/management_data_retrieval.py", line 18, in get_management_data
    all_managements = get_management_records(start_date, end_date)
  File "/Users/dlebauer/terraref/reference-data/experiment-trait-data-visualizer/api_data_retrieval/api_data_helpers.py", line 66, in get_management_records
    return get_records('managements', start_date, end_date, interval_retrieval=interval_retrieval)
  File "/Users/dlebauer/terraref/reference-data/experiment-trait-data-visualizer/api_data_retrieval/api_data_helpers.py", line 48, in get_records
    records += api_data["data"]
KeyError: 'data'
127.0.0.1 - - [09/May/2017 23:15:42] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [09/May/2017 23:15:42] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by dlebauer** [comment]
@yanliu-chn how can I run this app on ROGER? It is a python flask web application. 

I ... think ... I put the dependencies under ~/.pip/ so if I run

```
module load python/3.4.2
export PYTHONPATH=/gpfs/smallblockFS/home/dlebauer/.pip/sw/python/3.4.2/lib/python3.4/site-packages:$PYTHONPATH
python3 app.py
``` 

it says that it is being served at http://127.0.0.1:5000/. This should be served at https://terraref.ncsa.illinois.edu/webapps/ua-mac/experiment-trait-data-visualizer_sample/

```sh
cd /gpfs/largeblockFS/projects/arpae/terraref/sites/ua-mac/www
git clone git@github.com:terraref/reference-data
cd reference-data
git fetch origin 
git checkout -b feature origin/feature
cd experiment-trait-data-visualizer_sample
python -m pip install -r requirements.txt --root ~/.pip/
python3 app.py
```

**Comment by yanliu-chn** [comment]
I’m not sure if I understand the issue. Is this running on openstack or as a hpc job? I’m out of office today and tomorrow. So I’m cc’ing Jeff. Thanks! -Yan

**Comment by nickheyek** [comment]
The reason you are getting that error is because you need to set an environmental variable for BETYdbKey to make an API call.

**Comment by dlebauer** [comment]
@yanliu-chn and @jterstriep I've moved discussion of deployment to https://github.com/terraref/computing-pipeline/issues/311

@nickheyek 
```
export BETYdbKey=`cat ~/.betykey`
``` 

seems to have worked. thanks! (ps. how long should this take?)

**Comment by nickheyek** [comment]
Great! Sorry for the problems. Should be a few minutes.

**Comment by dlebauer** [comment]
@nickheyek I ran it, waited about 15 min, and the page wouldn't load. So I stopped it (ctrl+c) and restarted (python3 app.py) and now get this error at the end of the trace:

>   File "/Users/dlebauer/anaconda/envs/python3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/dlebauer/anaconda/envs/python3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 92300930 (char 92300929)
127.0.0.1 - - [10/May/2017 09:29:16] "GET / HTTP/1.1" 500 -json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 92300930 (char 92300929)
127.0.0.1 - - [10/May/2017 09:29:16] "GET / HTTP/1.1" 500 -

**Comment by dlebauer** [comment]
@yanliu-chn and @jterstriep sounds like @robkooper and @nickheyek already set up a container. Sorry - didn't realize this.

**Pull request closed without merging**
